# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bdcb8680eb7a78f9f72c7c94d4ebae867b2fb0b488f818032395d031c5b78038b3ab08ed19a15ce36fea5bf2160366b03fcc61998d0c51733986e45e5a08746

test:
  secret_key_base: 6fc21ee6d77c6666d35bf0a7ef11e781a9fc4979e06db491f5ca81486cdd2e5dfe91673d42092009c7be394310f1a926be19a03bb0cd859fdb5e3f01d016e8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
